export const enum UnitEffect
{
    NONE                = 0,
    SPOTLIGHT           = 1,
    HOVERBOARD_BLUE     = 2,
    HOVERCAR_BLUE       = 3,
    SPARKLES            = 4,
    TORCH               = 5,
    JETPACK             = 6,
    BUTTERFLIES         = 7,
    FIREFLIES           = 8,
    HEARTS              = 9,
    FLIES               = 10,
    GREEN               = 11,
    ICE                 = 12,
    GHOST               = 13,
    HOVERBOARD_PINK     = 14,
    HOVERBOARD_YELLOW   = 15,
    MIC                 = 16,
    HOVERCAR_PINK       = 17,
    HOVERCAR_YELLOW     = 18,
    POLICE_CAR          = 19,
    AMBULANCE           = 20,
    HORSE_SADDLE        = 77
}