export const enum IncomingHeader
{
    CROSS_DOMAIN                = 26979, //
    RELEASE_VERSION             = 4000, //
    CLIENT_VARIABLES            = 1053, //
    CLIENT_PERFORMANCE          = 3230, //
    MACHINE_ID                  = 2490, //
    SECURITY_TICKET             = 2419, //
    EVENT_TRACKER               = 3457, //
    CLIENT_LATENCY              = 2594,
    USER_INFO                   = 357, //
    USER_CLUB                   = 3166, //
    USER_PROFILE                = 3265, //
    USER_CREDITS                = 273, //
    USER_RELATIONSHIPS          = 2138, //
    USER_CURRENT_BADGES         = 2091, //
    USER_FIGURE                 = 2730, //
    USER_SETTINGS               = 2388, //
    USER_SANCTION_STATUS        = 582,
    MESSENGER_INIT              = 2781, //
    MESSENGER_SEARCH            = 1210, //
    MESSENGER_REQUEST           = 3157, //
    MESSENGER_REQUESTS          = 2448, //
    MESSENGER_UPDATE            = 1523,
    MESSENGER_ACCEPT            = 137, //
    MESSENGER_REMOVE            = 1689, //
    MESSENGER_DECLINE           = 2890, //
    MESSENGER_CHAT              = 3567, //
    NAVIGATOR_INIT              = 2110, //
    NAVIGATOR_SEARCH            = 3943, //
    NAVIGATOR_SETTINGS          = 1782, //
    NAVIGATOR_CATEGORIES        = 3027, //
    NAVIGATOR_ROOMS             = 249, //
    IGNORED_USERS               = 1047,
    GetUserFlatCatsMessageEvent = 2570,
    FIND_FRIENDS                = 516, //
    HOTELVIEW_CAMPAIGNS         = 2912, //
    HOTELVIEW_ARTICLES          = 1827, //
    GAMES_INIT                  = 2914, //
    GAMES_LIST                  = 741
}