export const enum OutgoingHeader
{
    MACHINE_ID                 = 1488,
    SECURITY_TICKET_OK         = 2491,
    USER_RIGHTS                = 2033,
    USER_HOME_ROOM             = 2875,
    USER_INFO                  = 2725,
    USER_CLUB                  = 954,
    USER_CLOTHING              = 3315,
    USER_PROFILE               = 3898,
    USER_FIGURE                = 1450,
    USER_CREDITS               = 3475,
    USER_SETTINGS              = 513,
    USER_SANCTION_STATUS       = 3679,
    NAVIGATOR_SETTINGS         = 518,
    NAVIGATOR_METADATA         = 3052,
    NAVIGATOR_LIFTED           = 3104,
    NAVIGATOR_COLLAPSED        = 1543,
    NAVIGATOR_SEARCH           = 2690,
    NAVIGATOR_SEARCHES         = 3984,
    NAVIGATOR_EVENT_CATEGORIES = 3244,
    MESSENGER_INIT             = 1605,
    MESSENGER_FRIENDS          = 3130,
    MESSENGER_SEARCH           = 973,
    MESSENGER_REQUEST          = 2219,
    MESSENGER_REQUEST_ERROR    = 892,
    MESSENGER_REQUESTS         = 280,
    MESSENGER_UPDATE           = 2800,
    MESSENGER_CHAT             = 1587,
    MESSENGER_CHAT_ERROR       = 896,
    MOD_TOOL                   = 2696,
    GENERIC_ALERT              = 3801
}